<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('settings')->delete();
        
        DB::table('settings')->insert([
            [
                'id' => 1,
                'name' => 'local_storage_validation',
                'value' => 'jpg,jpeg,png,xlsx,xls,csv,pdf',
                'created_by' => 1,
                'created_at' => '2026-03-10 05:00:46',
                'updated_at' => '2026-03-10 05:00:46',
            ],
            [
                'id' => 2,
                'name' => 'wasabi_storage_validation',
                'value' => 'jpg,jpeg,png,xlsx,xls,csv,pdf',
                'created_by' => 1,
                'created_at' => '2026-03-10 05:00:46',
                'updated_at' => '2026-03-10 05:00:46',
            ],
            [
                'id' => 3,
                'name' => 's3_storage_validation',
                'value' => 'jpg,jpeg,png,xlsx,xls,csv,pdf',
                'created_by' => 1,
                'created_at' => '2026-03-10 05:00:46',
                'updated_at' => '2026-03-10 05:00:46',
            ],
            [
                'id' => 4,
                'name' => 'local_storage_max_upload_size',
                'value' => 2048000,
                'created_by' => 1,
                'created_at' => '2026-03-10 05:00:46',
                'updated_at' => '2026-03-10 05:00:46',
            ],
            [
                'id' => 5,
                'name' => 'wasabi_max_upload_size',
                'value' => 2048000,
                'created_by' => 1,
                'created_at' => '2026-03-10 05:00:46',
                'updated_at' => '2026-03-10 05:00:46',
            ],
            [
                'id' => 6,
                'name' => 's3_max_upload_size',
                'value' => 2048000,
                'created_by' => 1,
                'created_at' => '2026-03-10 05:00:46',
                'updated_at' => '2026-03-10 05:00:46',
            ],
            [
                'id' => 7,
                'name' => 'company_logo_dark',
                'value' => 'logo-dark.png',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'company_logo_light',
                'value' => 'logo-light.png',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'company_favicon',
                'value' => 'favicon.png',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'title_text',
                'value' => 'ANIMAZON',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'footer_text',
                'value' => 'ANIMAZON',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'default_language',
                'value' => 'en',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'color',
                'value' => '#00c1de',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'color_flag',
                'value' => 'false',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'cust_theme_bg',
                'value' => 'on',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'SITE_RTL',
                'value' => 'off',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'cust_darklayout',
                'value' => 'on',
                'created_by' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'name' => 'site_currency',
                'value' => 'INR',
                'created_by' => 6,
                'created_at' => '2026-03-10 06:33:41',
                'updated_at' => '2026-03-10 06:33:41',
            ],
            [
                'id' => 35,
                'name' => 'site_currency_symbol',
                'value' => 'Ôé╣',
                'created_by' => 6,
                'created_at' => '2026-03-10 06:33:41',
                'updated_at' => '2026-03-10 06:33:41',
            ],
            [
                'id' => 36,
                'name' => 'decimal_number',
                'value' => 2,
                'created_by' => 6,
                'created_at' => '2026-03-10 06:33:41',
                'updated_at' => '2026-03-10 06:33:41',
            ],
            [
                'id' => 37,
                'name' => 'float_number',
                'value' => 'comma',
                'created_by' => 6,
                'created_at' => '2026-03-10 06:33:41',
                'updated_at' => '2026-03-10 06:33:41',
            ],
            [
                'id' => 38,
                'name' => 'decimal_separator',
                'value' => 'dot',
                'created_by' => 6,
                'created_at' => '2026-03-10 06:33:41',
                'updated_at' => '2026-03-10 06:33:41',
            ],
            [
                'id' => 39,
                'name' => 'thousand_separator',
                'value' => 'dot',
                'created_by' => 6,
                'created_at' => '2026-03-10 06:33:41',
                'updated_at' => '2026-03-10 06:33:41',
            ],
            [
                'id' => 40,
                'name' => 'title_text',
                'value' => 'ANIMAZON',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 41,
                'name' => 'footer_text',
                'value' => 'ANIMAZON',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'default_language',
                'value' => 'en',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'enable_signup',
                'value' => 'on',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'color',
                'value' => '#00c1de',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'color_flag',
                'value' => 'true',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 46,
                'name' => 'primary_color',
                'value' => '#00c1de',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 47,
                'name' => 'secondary_color',
                'value' => '#ff6122',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 48,
                'name' => 'cust_theme_bg',
                'value' => 'on',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 49,
                'name' => 'SITE_RTL',
                'value' => 'off',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'display_landing_page',
                'value' => 'off',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'gdpr_cookie',
                'value' => 'off',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'email_verification',
                'value' => 'off',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'cust_darklayout',
                'value' => 'on',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'mail_driver',
                'value' => 'smtp',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 55,
                'name' => 'mail_host',
                'value' => 'smtp.hostinger.com',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 56,
                'name' => 'mail_port',
                'value' => 465,
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 57,
                'name' => 'mail_username',
                'value' => 'info@animazon.in',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 58,
                'name' => 'mail_password',
                'value' => 'Nov06@Erode',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 59,
                'name' => 'mail_encryption',
                'value' => 'ssl',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 60,
                'name' => 'mail_from_address',
                'value' => 'info@animazon.in',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 61,
                'name' => 'mail_from_name',
                'value' => 'ANIMAZON',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 62,
                'name' => 'mail_driver',
                'value' => 'smtp',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 63,
                'name' => 'mail_host',
                'value' => 'smtp.hostinger.com',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 64,
                'name' => 'mail_port',
                'value' => 465,
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 65,
                'name' => 'mail_username',
                'value' => 'info@animazon.in',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 66,
                'name' => 'mail_password',
                'value' => 'Nov06@Erode',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 67,
                'name' => 'mail_encryption',
                'value' => 'ssl',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 68,
                'name' => 'mail_from_address',
                'value' => 'info@animazon.in',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 69,
                'name' => 'mail_from_name',
                'value' => 'ANIMAZON',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 70,
                'name' => 'cust_darklayout',
                'value' => 'on',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 71,
                'name' => 'cust_theme_bg',
                'value' => 'on',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 72,
                'name' => 'color_flag',
                'value' => 'true',
                'created_by' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 73,
                'name' => 'site_currency',
                'value' => 'INR',
                'created_by' => 2,
                'created_at' => '2026-04-25 10:59:09',
                'updated_at' => '2026-04-25 10:59:09',
            ],
            [
                'id' => 74,
                'name' => 'site_currency_symbol',
                'value' => '₹',
                'created_by' => 2,
                'created_at' => '2026-04-25 10:59:10',
                'updated_at' => '2026-04-25 10:59:10',
            ],
            [
                'id' => 75,
                'name' => 'decimal_number',
                'value' => 2,
                'created_by' => 2,
                'created_at' => '2026-04-25 10:59:10',
                'updated_at' => '2026-04-25 10:59:10',
            ],
            [
                'id' => 76,
                'name' => 'float_number',
                'value' => 'comma',
                'created_by' => 2,
                'created_at' => '2026-04-25 10:59:10',
                'updated_at' => '2026-04-25 10:59:10',
            ],
            [
                'id' => 77,
                'name' => 'decimal_separator',
                'value' => 'dot',
                'created_by' => 2,
                'created_at' => '2026-04-25 10:59:10',
                'updated_at' => '2026-04-25 10:59:10',
            ],
            [
                'id' => 78,
                'name' => 'thousand_separator',
                'value' => 'dot',
                'created_by' => 2,
                'created_at' => '2026-04-25 10:59:11',
                'updated_at' => '2026-04-25 10:59:11',
            ],
            [
                'id' => 79,
                'name' => 'portfolios',
                'value' => '[{"title":"LenzBreeze","type":"website","website_url":"https://www.lenzbreeze.com/","badge_text":"E-Commerce","tech_stack":"Laravel, Vue.js"},{"title":"Dhanvanthiri","type":"website","website_url":"https://dhanvanthrifoods.com/","badge_text":"Business","tech_stack":"Laravel, Bootstrap"},{"title":"Loan Track","type":"website","website_url":"https://app.animazon.in/home","badge_text":"Product","tech_stack":"Laravel, Livewire, Tailwind CSS","category":"Websites","description":"Advanced loan tracking and management system for real-time tracking, reporting, and dashboard analytics."},{"title":"Wildlife Leather","description":"A luxury e-commerce storefront for premium leather goods.","category":"Websites","type":"website","website_url":"https://wildlifeleather.in/","completion_date":"2025-02-01","tech_stack":"Shopify, Liquid, JS"},{"title":"JRNEX","type":"website","website_url":"https://schoolingapp.animazon.in/","badge_text":"Education","tech_stack":"Flutter, Laravel","category":"Websites","description":"An innovative educational platform for modern schooling."},{"title":"ipcatn.com","description":"A comprehensive platform for the Indian Paint & Coating Association.","category":"Websites","type":"website","website_url":"https://ipcatn.com/login/","completion_date":"2025-09-01","tech_stack":"Laravel, Vue.js, Tailwind CSS"},{"title":"How MCB Works \u2014 Circuit Breaker Explained","description":"We engineered a detailed exploded-view animation of a Miniature Circuit Breaker.","category":"3D Animation","type":"video","video_url":"https://youtu.be/nd6IVLni9lE","tech_stack":"Blender, After Effects"},{"title":"3D Interior Visualization","description":"A photorealistic architectural walkthrough showcasing modern interior design with dynamic lighting.","category":"3D Animation","type":"video","video_url":"https://youtu.be/xgGfezI8WXs","tech_stack":"3ds Max, V-Ray"},{"title":"Trojan Horse Inside Your Body","description":"A cinematic medical animation illustrating how pathogens infiltrate the human immune system.","category":"3D Animation","type":"video","video_url":"https://youtu.be/HkTKc1tBlUY","tech_stack":"Maya, Arnold"},{"title":"Dental Implants \u2014 Surgical Procedure","category":"3D Animation","type":"video","video_url":"https://youtu.be/t77d2ycQYO8"},{"title":"Nuclear Power Plant \u2014 How It Works","category":"3D Animation","type":"video","video_url":"https://youtu.be/XYjSwK8EI9M"},{"title":"Wind Turbine \u2014 Engineering Breakdown","category":"3D Animation","type":"video","video_url":"https://youtu.be/wnR4naujJQ0"},{"title":"Stepper Motor \u2014 Internal Mechanics","category":"3D Animation","type":"video","video_url":"https://youtu.be/wBloyozjceI"},{"title":"DC Motor \u2014 Working Principle","category":"3D Animation","type":"video","video_url":"https://youtu.be/D9jdk2PQD98"},{"title":"How Electricity Works","category":"3D Animation","type":"video","video_url":"https://youtu.be/wE0k8Hxr9_Q"},{"title":"IRIS \u2014 Human Eye Anatomy","category":"3D Animation","type":"video","video_url":"https://youtu.be/4a_diCTcvp4"},{"title":"360\u00b0 Auditorium Visualization","category":"3D Animation","type":"video","video_url":"https://youtu.be/ASu3lPqHiLw"},{"title":"How Touch Screens Work","category":"3D Animation","type":"video","video_url":"https://youtu.be/l-v1uJbzMEo"},{"title":"How a Grenade Works \u2014 MK2 Explained","category":"3D Animation","type":"video","video_url":"https://youtu.be/o3JYBhp9RH8"},{"title":"Rudra Spirit","type":"website","category":"Websites","website_url":"https://rudraspirit.com/","badge_text":"Spiritual E-Commerce","tech_stack":"Laravel, TailwindCSS","description":"A premium spiritual e-commerce platform for sacred products."}]',
                'created_by' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
