<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CostCalculatorQuestionsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('cost_calculator_questions')->delete();
        
        DB::table('cost_calculator_questions')->insert([
            [
                'id' => 1,
                'project_type_id' => 2,
                'question' => 'Video Duration',
                'description' => 'Base package covers up to 15 seconds of rendered animation.',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 2,
                'project_type_id' => 2,
                'question' => 'Animation Complexity',
                'description' => 'What type of objects or characters will be animated?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 3,
                'project_type_id' => 2,
                'question' => 'Do you have 3D models ready?',
                'description' => 'If you already have production-ready models, we can skip asset creation.',
                'type' => 'single_select',
                'order' => 3,
                'required' => 1,
                'category' => 'assets',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 4,
                'project_type_id' => 2,
                'question' => 'Render Resolution & Quality',
                'description' => 'Higher resolution increases render time significantly.',
                'type' => 'single_select',
                'order' => 4,
                'required' => 1,
                'category' => 'quality',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 5,
                'project_type_id' => 2,
                'question' => 'Add-ons & Deliverables',
                'description' => 'Select all extras you need.',
                'type' => 'multi_select',
                'order' => 5,
                'required' => 1,
                'category' => 'extras',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 6,
                'project_type_id' => 3,
                'question' => 'Detail Level / Poly Count',
                'description' => 'Higher detail = more polygons = more time.',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 7,
                'project_type_id' => 3,
                'question' => 'Number of Models',
                'description' => 'How many models do you need at this detail level?',
                'type' => 'input',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 8,
                'project_type_id' => 3,
                'question' => 'Material & Texturing',
                'description' => 'What level of surface detail do you need?',
                'type' => 'single_select',
                'order' => 3,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 9,
                'project_type_id' => 3,
                'question' => 'Additional Services',
                'description' => 'Select any extras needed.',
                'type' => 'multi_select',
                'order' => 4,
                'required' => 1,
                'category' => 'extras',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 10,
                'project_type_id' => 6,
                'question' => 'How many pages do you need?',
                'description' => 'Base includes 5 pages: Home, About, Services, Contact, and one more of your choice.',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 11,
                'project_type_id' => 6,
                'question' => 'Design Quality',
                'description' => 'How polished should the visual design be?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'design',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 12,
                'project_type_id' => 6,
                'question' => 'Technology / CMS Preference',
                'description' => 'How do you want to manage your content?',
                'type' => 'single_select',
                'order' => 3,
                'required' => 1,
                'category' => 'stack',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 13,
                'project_type_id' => 6,
                'question' => 'Hosting & Server Setup',
                'description' => 'Where should we deploy your website? (Annual hosting costs)',
                'type' => 'single_select',
                'order' => 4,
                'required' => 1,
                'category' => 'hosting',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 14,
                'project_type_id' => 6,
                'question' => 'Integrations & Features',
                'description' => 'Select everything you need. Contact form is included free.',
                'type' => 'multi_select',
                'order' => 5,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 15,
                'project_type_id' => 6,
                'question' => 'Delivery Timeline',
                'description' => 'When do you need the site ready?',
                'type' => 'single_select',
                'order' => 6,
                'required' => 1,
                'category' => 'timeline',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 16,
                'project_type_id' => 6,
                'question' => 'Annual Maintenance Contract (AMC)',
                'description' => 'Do you need ongoing support and updates after launch?',
                'type' => 'single_select',
                'order' => 7,
                'required' => 1,
                'category' => 'extras',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:36',
                'updated_at' => '2026-04-17 05:45:36',
            ],
            [
                'id' => 17,
                'project_type_id' => 7,
                'question' => 'Store Size & Scale (Product Limit)',
                'description' => 'How many products will your store support?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 18,
                'project_type_id' => 7,
                'question' => 'E-Commerce Platform',
                'description' => 'Which platform should we build on?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'stack',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 19,
                'project_type_id' => 7,
                'question' => 'Payment Options',
                'description' => 'Select all payment methods you need.',
                'type' => 'multi_select',
                'order' => 3,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 20,
                'project_type_id' => 7,
                'question' => 'Hosting & AMC Support',
                'description' => 'Where should we deploy and maintain it?',
                'type' => 'single_select',
                'order' => 4,
                'required' => 1,
                'category' => 'hosting',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 21,
                'project_type_id' => 7,
                'question' => 'Delivery Timeline',
                'description' => 'When do you need the store live?',
                'type' => 'single_select',
                'order' => 5,
                'required' => 1,
                'category' => 'timeline',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 22,
                'project_type_id' => 8,
                'question' => 'Application Type',
                'description' => 'What kind of web application are you building?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 23,
                'project_type_id' => 8,
                'question' => 'User Roles & Permissions',
                'description' => 'How many distinct user roles do you need?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 24,
                'project_type_id' => 8,
                'question' => 'Core Features',
                'description' => 'Select all the features your application needs.',
                'type' => 'multi_select',
                'order' => 3,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 25,
                'project_type_id' => 8,
                'question' => 'UI/UX Design Level',
                'description' => 'How polished should the interface be?',
                'type' => 'single_select',
                'order' => 4,
                'required' => 1,
                'category' => 'design',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 26,
                'project_type_id' => 8,
                'question' => 'Deployment Infrastructure',
                'description' => 'Where should the application run?',
                'type' => 'single_select',
                'order' => 5,
                'required' => 1,
                'category' => 'hosting',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 27,
                'project_type_id' => 9,
                'question' => 'Landing Page Purpose',
                'description' => 'What is the primary goal of this page?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 28,
                'project_type_id' => 9,
                'question' => 'Design Approach',
                'description' => 'How should the page look and feel?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'design',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 29,
                'project_type_id' => 9,
                'question' => 'Features & Integrations',
                'description' => 'Select everything you need.',
                'type' => 'multi_select',
                'order' => 3,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 30,
                'project_type_id' => 9,
                'question' => 'Delivery Speed',
                'description' => 'When do you need this page live?',
                'type' => 'single_select',
                'order' => 4,
                'required' => 1,
                'category' => 'timeline',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 31,
                'project_type_id' => 12,
                'question' => 'Target Platforms',
                'description' => 'Which mobile platforms do you need?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 32,
                'project_type_id' => 12,
                'question' => 'App Complexity',
                'description' => 'How many screens and flow complexity?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 33,
                'project_type_id' => 12,
                'question' => 'App Features',
                'description' => 'Select all features you need.',
                'type' => 'multi_select',
                'order' => 3,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 34,
                'project_type_id' => 12,
                'question' => 'Design Level',
                'description' => 'How polished should the UI be?',
                'type' => 'single_select',
                'order' => 4,
                'required' => 1,
                'category' => 'design',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 35,
                'project_type_id' => 12,
                'question' => 'App Store Submission',
                'description' => 'Should we handle publishing to app stores?',
                'type' => 'single_select',
                'order' => 5,
                'required' => 1,
                'category' => 'publishing',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 36,
                'project_type_id' => 12,
                'question' => 'Backend & API',
                'description' => 'Does the app need a server-side backend?',
                'type' => 'single_select',
                'order' => 6,
                'required' => 1,
                'category' => 'hosting',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 37,
                'project_type_id' => 13,
                'question' => 'Target Platform',
                'description' => 'Which tablet ecosystem?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 38,
                'project_type_id' => 13,
                'question' => 'App Complexity',
                'description' => 'How many screens and features?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 39,
                'project_type_id' => 13,
                'question' => 'Tablet-Specific Features',
                'description' => 'Select all features you need.',
                'type' => 'multi_select',
                'order' => 3,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 40,
                'project_type_id' => 16,
                'question' => 'Game Genre',
                'description' => 'What type of casual game?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 41,
                'project_type_id' => 16,
                'question' => 'Target Platform',
                'description' => 'Where should the game run?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 42,
                'project_type_id' => 16,
                'question' => 'Number of Levels',
                'description' => 'How much content should the game have?',
                'type' => 'single_select',
                'order' => 3,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 43,
                'project_type_id' => 16,
                'question' => 'Game Features',
                'description' => 'Select additional features.',
                'type' => 'multi_select',
                'order' => 4,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 44,
                'project_type_id' => 16,
                'question' => 'Art Style',
                'description' => 'What visual look do you want?',
                'type' => 'single_select',
                'order' => 5,
                'required' => 1,
                'category' => 'design',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 45,
                'project_type_id' => 17,
                'question' => 'Game Genre',
                'description' => 'What type of 3D game?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 46,
                'project_type_id' => 17,
                'question' => 'Target Platform',
                'description' => 'Where will the game run?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 47,
                'project_type_id' => 17,
                'question' => 'Game Scope & Content',
                'description' => 'How large is the game world?',
                'type' => 'single_select',
                'order' => 3,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 48,
                'project_type_id' => 17,
                'question' => 'Game Features',
                'description' => 'Select all features needed.',
                'type' => 'multi_select',
                'order' => 4,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 49,
                'project_type_id' => 17,
                'question' => 'Art Style',
                'description' => 'What visual quality level?',
                'type' => 'single_select',
                'order' => 5,
                'required' => 1,
                'category' => 'design',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 50,
                'project_type_id' => 17,
                'question' => 'Game Engine',
                'description' => 'Which engine should we use?',
                'type' => 'single_select',
                'order' => 6,
                'required' => 1,
                'category' => 'stack',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 51,
                'project_type_id' => 18,
                'question' => 'Experience Type',
                'description' => 'What kind of AR/VR experience?',
                'type' => 'single_select',
                'order' => 1,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 52,
                'project_type_id' => 18,
                'question' => 'Target Device',
                'description' => 'Which hardware platform?',
                'type' => 'single_select',
                'order' => 2,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 53,
                'project_type_id' => 18,
                'question' => 'Experience Duration',
                'description' => 'How long should the experience last?',
                'type' => 'single_select',
                'order' => 3,
                'required' => 1,
                'category' => 'scope',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
            [
                'id' => 54,
                'project_type_id' => 18,
                'question' => 'XR Features',
                'description' => 'Select all capabilities needed.',
                'type' => 'multi_select',
                'order' => 4,
                'required' => 1,
                'category' => 'features',
                'active' => 1,
                'created_at' => '2026-04-17 05:45:37',
                'updated_at' => '2026-04-17 05:45:37',
            ],
        ]);
    }
}
